---
# Create an instance on NeCTAR, define all the valiables, some of the varibale results are from other roles, such as security groups(a list of group names), volumes(a list of volume ids)
- name: Create an instance
  os_server:
    name: '{{ item.instance_name }}'
    image: '{{ item.instance_image }}'
    key_name: '{{ item.instance_key_name }}'
    flavor: '{{ item.instance_flavor }}'
    network: '{{ networks }}'
    availability_zone: '{{ availability_zone }}'
    security_groups: '{{ sg_names }}'
    auto_floating_ip: yes
    wait: yes
    timeout: 600
    state: present
  register: os_instance
  loop: '{{ instances }}'
- debug:
    msg: "Instance {{ instance_name }} has been created. IP address is {{ os_instance.openstack.public_v4 }}"
  when: os_instance.openstack is defined
