---
- name: Add an Apt signing key, uses whichever key is at the URL
  become: yes
  apt_key:
    url: https://couchdb.apache.org/repo/bintray-pubkey.asc
    state: present

- name: Add config
  become: yes
  lineinfile:
    path: /etc/apt/sources.list
    line: 'deb https://apache.bintray.com/couchdb-deb bionic main'
    create: yes

- name: apt update
  apt: update_cache=yes cache_valid_time=3600
  register: apt_result
  until: apt_result|success
  retries: 3
  delay: 1
  sudo: yes
  ignore_errors: yes

- name: retry if needed using command apt-get update
  command: apt-get update
  sudo: yes
  when: apt_result|failed

- name: install couchdb
  become: yes
  apt:
    name: ['couchdb']
    state: latest
  register: couchdb_install
  environment: "{{proxy_env}}"

- name: stop couchdb
  become: yes
  service:
    name: couchdb
    state: stopped

- name: change owner of couchdb executable
  become: yes
  file:
    state: directory
    mode: 0770
    owner: couchdb
    group: couchdb
    path: /opt/couchdb
    recurse: yes

- name: start couchdb
  become: yes
  service:
    name: couchdb
    state: started

- name: setup admins
  become: yes
  lineinfile:
    dest: /opt/couchdb/etc/local.ini
    state: present
    line: "{{ item.key }} = {{ item.value }}"
    regexp: "^{{ item.key }} = "
    insertafter: "^\\[admins\\]$"
  with_dict: "{{ couchdb_admins }}"
  notify: restart couchdb

- name: create configuration file
  become: yes
  template:
    src: local.ini
    dest: /opt/couchdb/etc/local.ini
    mode: 0770
    owner: couchdb
    group: couchdb
  notify: restart couchdb
