---
- name: Gather facts of remote host
  setup:
    gather_subset: all

- name: create dic
  tags: always
  become: yes
  file:
    path: "{{ py_dir }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: yes
    state: directory

- name: copy python file
  tags: always
  become: yes
  copy:
    src: "{{ cities }}"
    dest: "{{ py_dir }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 01777

- name: copy python file
  tags: always
  become: yes
  copy:
    src: "{{ client }}"
    dest: "{{ py_dir }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 01777

- name: copy python file
  tags: always
  become: yes
  copy:
    src: "{{ preprocess }}"
    dest: "{{ py_dir }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 01777

- name: copy python file
  tags: always
  become: yes
  copy:
    src: "{{ serverpy }}"
    dest: "{{ py_dir }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 01777

- name: copy python file
  tags: always
  become: yes
  copy:
    src: "{{ hostsfile }}"
    dest: "{{ py_dir }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 01777